### ISSUE TITLE
Whare 1psidts key

### ISSUE THREAD

**Issue by UW4IS** [x404xx/Gemini-CLI#3]
![IMG_20240510_191355](https://github.com/x404xx/Gemini-CLI/assets/97219180/79ef9e47-446c-48ab-a4c5-dd9bd92f5227)

Whare the key for psidts

**Comment by x404xx** [comment]
> ![IMG_20240510_191355](https://private-user-images.githubusercontent.com/97219180/329562896-79ef9e47-446c-48ab-a4c5-dd9bd92f5227.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDQ5MzksIm5iZiI6MTcxNTQwNDYzOSwicGF0aCI6Ii85NzIxOTE4MC8zMjk1NjI4OTYtNzllZjllNDctNDQ2Yy00OGFiLWE0YzUtZGQ5YmQ5MmY1MjI3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA1MTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyM2ZjMGYwODI1NjA0MjI5MTAwMDc1NjIxYTczOTIyZDE3MGQwMDUyMDY1Yjg3MTYxMTk1YTA5Y2NiNWJlNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lwOkoCgnJih6EpLbIrZb8iafv_QqLUVxidByhMFZ2xk)
> 
> Whare the key for psidts

You can add this extension (https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/). This is for Firefox.

After installing that extension, make sure you sign in with your Google account (https://gemini.google.com/?hl=en), then you can click on the Cookie-Editor. You can get that cookie from there.

![Screenshot (20240511-132056)](https://github.com/x404xx/Gemini-CLI/assets/114883816/2dbec83a-e5b0-4362-90a9-7aefcbd60c5b)

Enjoy.
